.TH "ISOMAN" "1" "April 2009" "" ""
.SH "NAME"
isoman \- a simple cd image manager

.SH "SYNOPSIS"
isoman [isofile] [outdir/device]
.SH "DESCRIPTION"
ISOMan is a simple script that allows you to manage CD images through the shell. But why reinvent the wheel? Because all of the popular alternatives out there are loaded with dependencies. ISOMan has no dependencies. Despite its size and simplicity, ISOMan effeciently automates the process of mounting, unmounting, extracting and burning ISO images.
.SH "OPTIONS"
.TP 
\fB\-m\fR, \fB\-\-mount\fR
Mount [isofile] to $VCD
.TP 
\fB\-u\fR, \fB\-\-umount\fR
Unmount [isofile]
.TP 
\fB\-x\fR, \fB\-\-extract\fR
Extract [isofile] to [outdir]
.TP 
\fB\-b\fR, \fB\-\-burn\fR
Burn [isofile] to [device]
.TP 
\fB\-h\fR, \fB\-\-help\fR
Display help
.TP 
\fB\-v\fR, \fB\-\-version\fR
Output version information and exit
.SH "AUTHORS"
Ghost1227
